spring:
  application:
    name: amao-market-eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka, http://127.0.0.1:8762/eureka, http://127.0.0.1:8763/eureka
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}

