
server:
  port: 10000

spring:
  application:
    name: amao-market-gateway-server
  cloud:
    gateway:
      enabled: true
      routes:
        - id: routes-amao-market-outward-service
          uri: lb://amao-market-outward-service
          predicates:
            - Path=/amao-market/api/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka, http://127.0.0.1:8762/eureka, http://127.0.0.1:8763/eureka
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}

